//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hangman.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hangman.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aaron Taylor-Johnson
        ///Abigail Breslin
        ///Adam Sandler
        ///Adele
        ///Adriana Barraza
        ///Adrianne Palicki
        ///Adrien Brody
        ///Al Pacino
        ///Alan Alda
        ///Alan Arkin
        ///Alan Rickman
        ///Albert Brooks
        ///Albert Finney
        ///Alec Baldwin
        ///Alex Pettyfer
        ///Alexander Skarsgard
        ///Alexandra Daddario
        ///Alexis Thorpe
        ///Ali Larter
        ///Alice Eve
        ///Alicia Vikander
        ///Amanda Bynes
        ///Amanda Crew
        ///Amanda Peet
        ///Amanda Seyfried
        ///Amber Heard
        ///Amy Adams
        ///Amy Ryan
        ///Amy Schumer
        ///Analeigh Tipton
        ///Andrew Garfield
        ///Andrew Lincoln
        ///Andrew Luck
        ///Andy Garcia
        ///Andy Samberg
        ///Andy S [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Celebrities {
            get {
                return ResourceManager.GetString("Celebrities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to abiyuch
        ///acerola
        ///acorn
        ///agave
        ///agents
        ///agutuk
        ///alfalfa
        ///amaranth
        ///animal
        ///apache
        ///apple
        ///apples
        ///applesauce
        ///apricot
        ///apricots
        ///arrowhead
        ///arrowroot
        ///artichokes
        ///artificial
        ///arugula
        ///ascidians
        ///asparagus
        ///avocados
        ///baby
        ///babyfood
        ///bacon
        ///bagel
        ///bagels
        ///baking
        ///balls
        ///balsam-pear
        ///bamboo
        ///bananas
        ///bar
        ///barbecue
        ///barley
        ///bars
        ///basil
        ///bean
        ///beans
        ///bear
        ///beef
        ///beerwurst
        ///beet
        ///beets
        ///berry
        ///besan
        ///beverage
        ///beverages
        ///biscuits
        ///bison
        ///bits
        ///bitter
        ///blackberries
        ///blackberry
        ///blackeyes
        ///blend
        ///blueberries
        ///blueberry
        ///bockwurst
        ///bologna
        ///borage
        ///bowl
        ///boysenberries
        ///bran
        ///bran [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string food {
            get {
                return ResourceManager.GetString("food", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 tone
        ///2-step garage
        ///4-beat
        ///4x4 garage
        ///8-bit
        ///acapella
        ///acid
        ///acid breaks
        ///acid house
        ///acid jazz
        ///acid rock
        ///acoustic music
        ///acousticana
        ///adult contemporary music
        ///african popular music
        ///african rumba
        ///afrobeat
        ///aleatoric music
        ///alternative country
        ///alternative dance
        ///alternative hip hop
        ///alternative metal
        ///alternative rock
        ///ambient
        ///ambient house
        ///ambient music
        ///americana
        ///anarcho punk
        ///anime music
        ///anti-folk
        ///apala
        ///ape haters
        ///arab pop
        ///arabesque
        ///arabic pop
        ///argentine rock
        ///ars antiqua
        ///ars nova
        ///art punk
        ///art rock
        ///ashiq
        ///asian american j [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string music_genres {
            get {
                return ResourceManager.GetString("music_genres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accountant
        ///Auditor
        ///Actor
        ///Actuary
        ///Adhesive Bonding Machine Operator
        ///Tender
        ///Administrative Law Judge
        ///Administrative Services Manager
        ///Adult Basic &amp; Secondary Education &amp; Literacy Teacher
        ///Instructor
        ///Advertising Sales Agent
        ///Advertising &amp; Promotions Manager
        ///Aerospace Engineering &amp; Operations Technician
        ///Aerospace Engineer
        ///Agent
        ///Business Managers of Artist
        ///Agricultural Engineer
        ///Agricultural Equipment Operator
        ///Agricultural Inspector
        ///Agricultural Sciences Teacher
        ///Agricultural Worker
        ///Agricultural &amp; Food Science Techni [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Occupations {
            get {
                return ResourceManager.GetString("Occupations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7 Aum Arivu 7th Sense  
        ///9 Nine  Short Film  
        ///10 Cloverfield Lane  
        ///12 to the Moon  
        ///20 Million Miles to Earth  
        ///20th Century Boys 
        ///24 Telegru  
        ///28 Days Later   
        ///28 Weeks Later  
        ///51  
        ///2012 Supernova  
        ///2012  
        ///2046  
        ///Mission Stardust  
        ///A Scanner Darkly  
        ///A Sound of Thunder  
        ///A Wind Named Amnesia    
        ///Abbott and Costello Go to Mars 
        ///Abbott and Costello Meet the Invisible Man  
        ///Absolon  
        ///After Earth 
        ///Aftershock  
        ///Alien3
        ///Alien Abduction  
        ///Alien Autopsy  
        ///Alien Hunter  
        ///Alien Intruder  
        ///A [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string scifi {
            get {
                return ResourceManager.GetString("scifi", resourceCulture);
            }
        }
    }
}
